steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - everyfuckingnoun
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --allow-unauthenticated
  - --entry-point=index
  - --runtime=go120
